//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace textis
{
    using System;
    using System.Collections.Generic;
    
    public partial class Project
    {
        public Project()
        {
            this.ProjectLine = new HashSet<ProjectLine>();
            this.Comment = new HashSet<Comment>();
            this.Upvote = new HashSet<Upvote>();
        }
    
        public int Id { get; set; }
        public string User { get; set; }
        public System.DateTime Date { get; set; }
        public string Name { get; set; }
        public string Status { get; set; }
        public string Url { get; set; }
    
        public virtual ICollection<ProjectLine> ProjectLine { get; set; }
        public virtual ICollection<Comment> Comment { get; set; }
        public virtual Category Category { get; set; }
        public virtual ICollection<Upvote> Upvote { get; set; }
    }
}
