//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace textis
{
    using System;
    using System.Collections.Generic;
    
    public partial class Upvote
    {
        public int Id { get; set; }
        public int ProjectId { get; set; }
        public string User { get; set; }
        public System.DateTime Date { get; set; }
    
        public virtual Project Project { get; set; }
    }
}
